defaults:
  - _self_

name: "DataCentre-Alpha"

simulation:
  snapshots_start: "2025-01-01"
  snapshots_end:   "2025-12-31"
  snapshot_freq:   "h"
  location:
    latitude: -27.4698
    longitude: 153.0251

financial:
  wacc: 0.105
  inflation_rate: 0.025
  project_lifetime: 25

compute:
  capacity_mw: 100
  water_use_effectiveness: 0.012
  power_use_effectiveness: 1.34
  load_realisation_factor: 0.75
  load_shift:
    enabled: true
    max_shift_hours: 8.0
    max_store_energy_factor: 0.0
    marginal_cost_shift: 0.0

supplies:
  water:
    cost_per_L: 0.00274
  gas:
    cost_per_GJ: 13.3 # gencost

grid_connection:
  capex_per_MW: 0.0 #11_500_000 #
  transmission_loss_factor: 0.975
  cost_per_MWh: 1000.0
  max_capacity_MW: 30
generation:
  onsite:
    ccgt:
      enabled: true
      capex_per_MW: 2_497_000 # Gencost
      opex_per_MW: 36_000 # Gencost
      water_kL_per_MWh: .7
      electrical_efficiency: 0.51 # Gencost
      block_size_MW: 10.0
      p_nom_extendable: true
      lifetime_years: 25
    battery:
      enabled: true
      capex_per_MWh: 606_000 # gencost
      opex_per_MWh: 15_050 # 2.5% of capex
      efficiency_charge: 0.95
      efficiency_discharge: 0.95
      max_hours: 4.0
      e_nom_extendable: true
      lifetime_years: 15
  ppa:
    - name: solar_farm
      technology: solar
      enabled: true
      lcoe: 52 #70 # LCOE gencost
      contract_margin: 0.15
      contract_capacity_fee_per_MW: 1.0
      profile:
        type: location_solar
        location:
          latitude: -27.4698
          longitude: 153.0251
        performance_ratio: 0.7
    - name: wind_farm
      technology: wind
      enabled: true
      lcoe: 78 #103.5 # LCOE gencost
      contract_margin: 0.15
      contract_capacity_fee_per_MW: 1.0
      profile:
        type: flat
        capacity_factor: 0.35 # Gencost


solver:
  name: "gurobi"
  options: {}
